### ISSUE TITLE
Is it possible to add support for $using:variable inside script block?

### ISSUE THREAD

**Issue by vors** [RamblingCookieMonster/Invoke-Parallel#14]
Consider:

``` powershell
$variable = "foo"; 1..2 | Invoke-Parallel {"$_ : $using:variable"}
```

Currently it outputs errors

**Comment by RamblingCookieMonster** [comment]
Cool idea!

@proxb has [a slick project](https://github.com/proxb/PoshRSJob/blob/Dev/PoshRSJob.psm1) that basically implements a job-like system for runspaces.  Looks like he implemented handling for $Using:variable fairly recently.

**Comment by RamblingCookieMonster** [comment]
[Duct taped that in](https://github.com/RamblingCookieMonster/Invoke-Parallel/tree/Using-Via-Boe), minimal to no changes to @proxb's code.  Relies on AST so PowerShell 3 and later only (reflects $Using in all other scenarios, so should meet user's expectations).  Not sure if PSParser would work for this to provide down-level support...

If you think the implementation makes sense let me know and we can merge it in.

Cheers!

**Comment by proxb** [comment]
I have probably an 80% solution for V2 $Using: support using PSParser. Pretty much everything up until adding the updated variables into the scriptblock as well as updating the Param() statement with the variables. If I can remember, I will grab the code from work and post in a Gist and link it here in case you wanted to take a swing at is as well.

**Comment by RamblingCookieMonster** [comment]
The basic implementation is in place - closing this out just to clean up [this mess](https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3ARamblingCookieMonster+sort%3Acreated-asc).  At this point, personally,  I'm not worried about PowerShell v2 support : )

Cheers!
