### ISSUE TITLE
Psexec through invoke-parallel?

### ISSUE THREAD

**Issue by hunterp12** [RamblingCookieMonster/Invoke-Parallel#21]
So I have a script that does some remote things using psexec. It looks like invoke-parallel doesn't like the psexec state. I'm assuming because it runs in a psexec process and not a powershell service and it throws a bunch og the get-runspacedata errors. It still runs really well. I would just like some way of getting some log information back to make sure everything ran smoothly. I've tried throwing in some start transcripts, but maybe I'm doing it wrong of the runspaces aren't allowing it to log correctly. Is there a way to get around the get-runspace errors when using psexec or a simpler way to get a return log for the various computers piped to the function?

Thanks for any help!
-Hunter

**Comment by RamblingCookieMonster** [comment]
Hello!

Take a look at [this thread](https://social.technet.microsoft.com/Forums/scriptcenter/en-US/46d92a72-c248-4b6f-9cab-ff047a6dd156/how-to-call-psexec-from-powershell?forum=ITCG) on TechNet.  This is related to the way psexec is written.

To work around it, some of the tricks in that thread should work.

![image](https://cloud.githubusercontent.com/assets/6377597/6793746/84445b8e-d19f-11e4-920a-ede92c218503.png)

By redirecting error to standard output for the psexec call, you avoid the errors.

There is rudimentary 'logging' - Tack on -Logfile \\path\to\a\log\file.txt

![image](https://cloud.githubusercontent.com/assets/6377597/6793775/e7bd6ca0-d19f-11e4-974c-15c8c8b27db5.png)

This could definitely be cleaned up and improved : )

Cheers!

**Comment by hunterp12** [comment]
Wow. Really great info. Thanks a lot!! This is exactly what I needed. Really enjoying the function. Thanks so much for the great tool and support!! First time putting it through some motions. Thanks again

**Comment by hunterp12** [comment]
FYI. I found out how to get start-transcript working within a script that you are using on Invoke-Parallel. Useful if you want better log information of what happens during the run. Just pipe to Out-Default and then Start-Transcript will pick up all the info from your script you have going in Invoke-Parallel. Just in case anyone else was curious
