### ISSUE TITLE
Running Out Of Memory

### ISSUE THREAD

**Issue by MikeBeckel** [RamblingCookieMonster/Invoke-Parallel#23]
When I use the module to process ~70K memory utilization increases steadily and does not go down.

`Invoke-Parallel -ScriptFile "C:\Scripts\Sync-AssetData.ps1" -InputObject $AssetList -Parameter $ConnectionInfo -Throttle 40`

**Comment by RamblingCookieMonster** [comment]
Hi Mike!

My apologies, got the notification for this and forgot to check it out.

I ran a quick test:

* Find a decent sized file.  Maybe ~ 1 MB
* Open Task Manager (or use PowerShell) and watch the memory usage for Invoke-Parallel
* Run a script that would cause crazy memory usage if there were a leak

```powershell

# I used this:
1..100 | Invoke-Parallel {Get-Content "C:\Windows\WindowsUpdate.log" | out-null}

```

Memory use grows several hundred megabytes, but drops down to where it started.

Might be worth digging into the code in Sync-AssetData - could there be a memory leak in that script?  You could test this by running it with a Foreach-Object.

Cheers!

**Comment by RamblingCookieMonster** [comment]
Hi Mike,

Closing this out, let me know if you find anything pointing to invoke-parallel rather than sync-assetdata.ps1

Thanks!
