### ISSUE TITLE
Crashing IDE / Powerhell console all the time

### ISSUE THREAD

**Issue by avishnyakov** [RamblingCookieMonster/Invoke-Parallel#30]
Hey guys, started using this script and hitting crashes most of the time.

Here is an example of Event log with EventID 1001. Same with PS ISE.
Any clue?
```
Fault bucket , type 0
Event Name: PowerShell
Response: Not available
Cab Id: 0

Problem signature:
P1: powershell.exe
P2: 10.0.10586.122
P3: System.IO.FileLoadException
P4: System.IO.FileLoadException
P5: unknown
P6: Microsoft.WSMan.Management.IGroupPolicyObject.Save
P7: unknown
P8: 
P9: 
P10: 
```

**Comment by RamblingCookieMonster** [comment]
Hi!

I recall running into a number of strange issues when attempting to speed up some group policy queries at $lastjob.  I suspect the grouppolicy module might be doing something ugly under the hood, but never verified with procmon.  Or, it could just be something sloppy on my end : )

Have you tried another runspace abstraction like [psparallel](https://github.com/powercode/PSParallel) or [poshrsjob](https://github.com/proxb/PoshRSJob)?  Might be worth seeing if similar issues come up using those tools.

Cheers!

**Comment by avishnyakov** [comment]
Yea, I see. I found a particular bit which got the run crashed. Does not seem to have anything to do with the Invoke-Parallel, of course.

And we don't use group policies things, just setting up directly the registry. Hm.. :)
