### ISSUE TITLE
This repo no longer works in AppVeyor - "Import-Module Pester" fails on PS Version 2

### ISSUE THREAD

**Issue by brow1920** [RamblingCookieMonster/Invoke-Parallel#42]
The title says it all pretty much - you haven't changed your code, but something about AppVeyor must have changed.  I just went through your blog post following the instructions and this was failing.  I implemented the fix for it in Pull Request #41 so you can use that... 

or else at least try to re-build your current solution and see if it still works... because it isn't working for those going through your blog post on how to set this up.  (if you know of a work-around, posting in your blog would be sweeeet!)

**Comment by RamblingCookieMonster** [comment]
Awesome, thanks for submitting the PR, will have to change this and mention in the blog - might tweak a thing or two, hence the wait, sorry about that!
