### ISSUE TITLE
index out of range, but I can not find which line throw exception

### ISSUE THREAD

**Issue by 176coding** [RamblingCookieMonster/Invoke-Parallel#43]
```
Get-RunspaceData : Index was out of range. Must be non-negative and less than 
the size of the collection.
Parameter name: index
At D:\UtilityTools\Invoke-Parallel.ps1:590 char:29
+                             Get-RunspaceData
+                             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], ArgumentOutOfRa 
   ngeException
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException,Get-RunspaceD 
   ata
 
```

**Comment by RamblingCookieMonster** [comment]
Hi!

Can you post the code that lead to this error?  Unfortunately, any error in your code will look like it's coming from 'Get-RunspaceData', given how we handle errors.  You'll find similar behavior in most runspace tools out there.

More details in the last 3 comments [of this issue](https://github.com/RamblingCookieMonster/Invoke-Parallel/issues/35/)

A good alternative is to use error handling in your code, and throw specific errors that you can use to figure out what part of the code is causing trouble.

Cheers!
