### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by 176coding** [RamblingCookieMonster/Invoke-Parallel#44]
```
Get-RunspaceData : Object reference not set to an instance of an object.
At D:\prism\CDaaS\UtilityTools\Invoke-Parallel.ps1:570 char:25
+                         Get-RunspaceData
+                         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], NullReferenceEx 
   ception
    + FullyQualifiedErrorId : System.NullReferenceException,Get-RunspaceData
 
```

**Comment by RamblingCookieMonster** [comment]
Hi!

Copy and paste from your other issue, which seems applicable:

Can you post the code that lead to this error?  Unfortunately, any error in your code will look like it's coming from 'Get-RunspaceData', given how we handle errors.  You'll find similar behavior in most runspace tools out there.

More details in the last 3 comments [of this issue](https://github.com/RamblingCookieMonster/Invoke-Parallel/issues/35/)

A good alternative is to use error handling in your code, and throw specific errors that you can use to figure out what part of the code is causing trouble.

Cheers!
