### ISSUE TITLE
Physical Memory usage

### ISSUE THREAD

**Issue by ghost** [RamblingCookieMonster/Invoke-Parallel#45]
This code hangs after processing about 150 objects, increases my thread count to over a 2000 and caps my physical memory out when running. The physical memory usage maintains at 31.8 GB after I have exited my powershell process and persists through the restart of another powershell process. How would you reconfigure the code to make it faster and stop hanging?

```
# contains a list of 10000 files. 
$files = Get-Content C:\Users\Administrator\Desktop\files.csv

$files | Invoke-Parallel -ImportModules -runspacetimeout 20 -nocloseontimeout -ScriptBlock{ 
Get-WinEvent -FilterHashtable @{Path=$_;id=4624;data="user.name1","user.name2","user.name3","user.name4","user.name5","user.name6" } | 
    Select-Object  -Property MachineName,RecordId, TimeCreated,Id,
    @{Name="SubjectUserSid"; Expression={$_.Properties[0].Value}},
    @{Name="SubjectUserName";Expression={$_.Properties[1].Value}},
    @{Name="SubjectDomainName";Expression={$_.Properties[2].Value}},
    @{Name="SubjectLogonId";Expression={$_.Properties[3].Value}},
    @{Name="TargetUserSid";Expression={$_.Properties[4].Value}},
    @{Name="TargetUserName"; Expression={$_.Properties[5].Value}},
    @{Name="TargetDomainName";Expression={$_.Properties[6].Value}},
    @{Name="TargetLogonId";Expression={$_.Properties[7].Value}},
    @{Name="LogonType";Expression={$_.Properties[8].Value}},
    @{Name="LogonProcessName";Expression={$_.Properties[9].Value}},
    @{Name="AuthenticationPackageName";Expression={$_.Properties[10].Value}},
    @{Name="WorkstationName";Expression={$_.Properties[11].Value}},
    @{Name="LogonGuid";Expression={$_.Properties[12].Value}},
    @{Name="TransmittedServices";Expression={$_.Properties[13].Value}},
    @{Name="LmPackageName";Expression={$_.Properties[14].Value}},
    @{Name="KeyLength";Expression={$_.Properties[15].Value}},
    @{Name="ProcessId";Expression={$_.Properties[16].Value}},
    @{Name="ProcessName";Expression={$_.Properties[17].Value}},
    @{Name="IP"; Expression={$_.Properties[18].Value}},
    @{Name="IpPort";Expression={$_.Properties[19].Value}} | Export-Csv -path "C:\users\Administrator\Desktop\folder1\full_$name.csv"  } -throttle 100 


```

**Comment by RaeldZues** [comment]
So, I dropped all throttling and pulled the export-csv into my scriptblock to attempt to export and drop that from memory. It seems as though its keeping it all in memory as I iterate over files, the memory usage doesnt drop back down.

**Comment by nati0** [comment]
Try to use the throttle and the runspace timeouts.
In one of his comments to the script, he mentions that not closing the thread/or using the switch you use(nocloseontimeout), **may** result in a memory leak.

The switches im talking about are these
Play around with the throttle until you hit something that looks like 95% used CPU
-throttle 15 -runspaceTimeout 30

**Comment by RamblingCookieMonster** [comment]
Oh!  Thought I replied to this!

So!  `-nocloseontimeout` will result in memory being eaten, but only for runspaces that time out.

You might try bumping up the `runspacetimeout` quite a bit, or using verbose to track if and when runspaces are timing out.

That said, if things are not timing out, chances are there's a memory leak in `Get-WinEvent`, or `Export-Csv`

Good luck!  Sorry for the delay!

**Comment by RamblingCookieMonster** [comment]
Closing this out, but let me know if you find out more, curious to know!  A good test might be to try this on a fully patched system with a newer version of PowerShell

Cheers!
