### ISSUE TITLE
Variable Creep

### ISSUE THREAD

**Issue by dustinross4** [RamblingCookieMonster/Invoke-Parallel#63]
This change fixed variable creep for me:

Line 215 on [the ps1](https://github.com/RamblingCookieMonster/Invoke-Parallel/blob/master/Invoke-Parallel/Invoke-Parallel.ps1)

Before change:
`            }).invoke()[0]`

After change:
`            },$true).invoke()[0]`

[source](https://learn-powershell.net/2018/01/28/dealing-with-runspacepool-variable-scope-creep-in-powershell/)

**Comment by vors** [comment]
Can you, please, explain what is variable creep? Also, want to fix PR for that?

**Comment by dustinross4** [comment]
the source link i supplied explains more thoroughly, but essentially sometimes values will carry over from parallel invocations

the change mentioned sets UseLocalScope to $True

**Comment by vors** [comment]
Ah thanks!
